import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://magento.softwaretestingboard.com/');
  await page.getByRole('combobox', { name: ' Search' }).click();
  await page.getByRole('combobox', { name: ' Search' }).fill('bag');
  await page.getByRole('combobox', { name: ' Search' }).press('Enter');
  await page.getByRole('link', { name: 'Voyage Yoga Bag' }).first().click();
  await page.getByRole('button', { name: 'Add to Cart' }).click();
  await page.getByRole('menuitem', { name: ' Women' }).click();
  await page.getByRole('link', { name: 'Hoodies & Sweatshirts' }).click();
  await page.getByRole('listitem').filter({ hasText: 'Circe Hooded Ice Fleece As' }).getByLabel('XL').click();
  await page.getByRole('listitem').filter({ hasText: 'Circe Hooded Ice Fleece As' }).getByLabel('Purple').click();
  await page.getByRole('listitem').filter({ hasText: 'Circe Hooded Ice Fleece As' }).locator('button').click();
  await page.getByRole('listitem').filter({ hasText: 'Eos V-Neck Hoodie As low as $' }).getByLabel('XL').click();
  await page.getByRole('listitem').filter({ hasText: 'Eos V-Neck Hoodie As low as $' }).getByLabel('Orange').click();
  await page.getByRole('listitem').filter({ hasText: 'Eos V-Neck Hoodie As low as $' }).locator('button').click();
  await page.getByRole('listitem').filter({ hasText: 'Helena Hooded Fleece As low' }).getByLabel('XL').click();
  await page.getByRole('option', { name: 'Yellow' }).click();
  await page.getByRole('listitem').filter({ hasText: 'Helena Hooded Fleece As low' }).locator('button').click();
  await page.getByRole('listitem').filter({ hasText: 'Ariel Roll Sleeve Sweatshirt' }).getByLabel('XL').click();
  await page.getByRole('listitem').filter({ hasText: 'Ariel Roll Sleeve Sweatshirt' }).getByLabel('Red').click();
  await page.getByRole('listitem').filter({ hasText: 'Ariel Roll Sleeve Sweatshirt' }).locator('button').click();
  await page.getByRole('listitem').filter({ hasText: 'Cassia Funnel Sweatshirt As' }).getByLabel('XL').click();
  await page.getByRole('listitem').filter({ hasText: 'Cassia Funnel Sweatshirt As' }).getByLabel('White').click();
  await page.getByRole('listitem').filter({ hasText: 'Cassia Funnel Sweatshirt As' }).locator('button').click();
  await page.getByRole('listitem').filter({ hasText: 'Phoebe Zipper Sweatshirt As' }).getByLabel('XL').click();
  await page.getByRole('listitem').filter({ hasText: 'Phoebe Zipper Sweatshirt As' }).getByLabel('White').click();
  await page.getByRole('listitem').filter({ hasText: 'Phoebe Zipper Sweatshirt As' }).locator('button').click();
  await page.getByRole('listitem').filter({ hasText: 'Daphne Full-Zip Hoodie Rating' }).getByLabel('XL').click();
  await page.getByRole('listitem').filter({ hasText: 'Daphne Full-Zip Hoodie Rating' }).getByLabel('Purple').click();
  await page.getByRole('listitem').filter({ hasText: 'Daphne Full-Zip Hoodie Rating' }).locator('button').click();
  await page.getByRole('listitem').filter({ hasText: 'Selene Yoga Hoodie Rating: 80' }).getByLabel('XL').click();
  await page.getByRole('listitem').filter({ hasText: 'Selene Yoga Hoodie Rating: 80' }).getByLabel('White').click();
  await page.getByRole('listitem').filter({ hasText: 'Selene Yoga Hoodie Rating: 80' }).locator('button').click();
  await page.getByRole('listitem').filter({ hasText: 'Miko Pullover Hoodie Rating:' }).getByLabel('XL').click();
  await page.getByRole('listitem').filter({ hasText: 'Miko Pullover Hoodie Rating:' }).getByLabel('Purple').click();
  await page.getByRole('listitem').filter({ hasText: 'Miko Pullover Hoodie Rating:' }).locator('button').click();
  await page.getByRole('listitem').filter({ hasText: 'Autumn Pullie Rating: 60% 3' }).getByLabel('XL').click();
  await page.getByRole('listitem').filter({ hasText: 'Autumn Pullie Rating: 60% 3' }).getByLabel('Red').click();
  await page.getByRole('listitem').filter({ hasText: 'Autumn Pullie Rating: 60% 3' }).locator('button').click();
  await page.getByRole('listitem').filter({ hasText: 'Hera Pullover Hoodie Rating:' }).getByLabel('XL').click();
  await page.getByRole('listitem').filter({ hasText: 'Hera Pullover Hoodie Rating:' }).getByLabel('Orange').click();
  await page.getByRole('listitem').filter({ hasText: 'Hera Pullover Hoodie Rating:' }).locator('button').click();
  await page.getByRole('listitem').filter({ hasText: 'Mona Pullover Hoodlie Rating' }).getByLabel('XL').click();
  await page.getByRole('listitem').filter({ hasText: 'Mona Pullover Hoodlie Rating' }).getByLabel('Purple').click();
  await page.getByRole('listitem').filter({ hasText: 'Mona Pullover Hoodlie Rating' }).locator('button').click();
  await page.getByRole('link', { name: ' My Cart 13 13 items' }).click();
  await page.getByRole('button', { name: 'Proceed to Checkout' }).click();
  await page.getByRole('tab', { name: 'of 13 Items in Cart ' }).click();
  await page.getByRole('textbox', { name: 'Email Address * Email Address' }).click();
  await page.getByRole('textbox', { name: 'Email Address * Email Address' }).fill('gunaguna20994@gmail.com');
  await page.getByRole('textbox', { name: 'First Name *' }).click();
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Guna@?2004');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.goto('https://magento.softwaretestingboard.com/checkout/#shipping');
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('button', { name: 'Place Order' }).click();
  await page.getByRole('link', { name: 'Continue Shopping' }).click();
});