import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://magento.softwaretestingboard.com/');
  await page.getByRole('link', { name: 'Sign In' }).click();
  await page.getByRole('textbox', { name: 'Email*' }).click();
  await page.getByRole('textbox', { name: 'Email*' }).fill('gunaguna20994@gmail.com');
  await page.getByRole('textbox', { name: 'Password* Password' }).click();
  await page.getByRole('textbox', { name: 'Password* Password' }).fill('Guna@?2004');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.getByRole('combobox', { name: ' Search' }).click();
  await page.getByRole('combobox', { name: ' Search' }).fill('bag');
  await page.getByRole('option', { name: 'bag', exact: true }).click();
  await page.getByRole('tab', { name: 'Category ' }).click();
  await page.getByRole('link', { name: 'Gear (7 item )' }).click();
  await page.getByLabel('Sort By').selectOption('price');
  await page.goto('https://magento.softwaretestingboard.com/catalogsearch/result/index/?cat=3&q=+bag&product_list_order=price');
  await page.getByRole('link', { name: 'Wayfarer Messenger Bag' }).first().click();
  await page.getByRole('button', { name: 'Add to Cart' }).click();
  await page.getByRole('link', { name: ' Add to Wish List' }).click();
  await page.getByRole('link', { name: 'My Orders' }).click();
  await page.getByRole('link', { name: 'My Account' }).click();
  await page.getByRole('combobox', { name: ' Search' }).click();
  await page.getByRole('combobox', { name: ' Search' }).fill('books');
  await page.getByRole('combobox', { name: ' Search' }).press('Enter');
  await page.getByRole('listitem').filter({ hasText: 'Driven Backpack Rating: 90% 2' }).locator('button').click();
  await page.getByRole('listitem').filter({ hasText: 'Endeavor Daytrip Backpack' }).locator('button').click();
  await page.getByRole('listitem').filter({ hasText: 'Crown Summit Backpack Rating' }).locator('button').click();
  await page.getByRole('link', { name: ' My Cart 4 4 items' }).click();
  await page.getByRole('button', { name: 'Proceed to Checkout' }).click();
});